
method: "sSVN_laplace" # "SGD_ensembles", "SGLD", "SVGD", "sSVGD", "SVN_laplace", "sSVN_laplace", "SVN_adam", "sSVN_adam"
is_stochastic: False

# seeds: [38,39,40,41,42] # 38 39 40 41 42

task: "power"

is_classification: False
task_dim: 1

lr: 1e-6
anneal: True

kernel_gamma: 1e-3 


data_location: "data/"
batch_size: 128

num_particles: 20
num_epochs: 50

model_selection_metric: 'MSE' # 'MSE' 'NLL' 

likelihood_std: 1

