
method: "SVN_laplace" # "SGD_ensembles", "SGLD", "SVGD", "sSVGD", "SVN_laplace", "sSVN_laplace", "SVN_adam", "sSVN_adam"
is_stochastic: False

# seeds: [38,39,40,41,42] # 38 39 40 41 42

task: "wine"

is_classification: False
task_dim: 1

lr: 1e-4
anneal: True

kernel_gamma: 1e-3 


data_location: "data/"
batch_size: 16

num_particles: 20
num_epochs: 30

model_selection_metric: 'NLL' # 'MSE' 'NLL' 

likelihood_std: 1

