
method: "SGLD" # "SGD_ensembles", "SGLD", "SVGD", "sSVGD", "SVN_laplace", "sSVN_laplace", "SVN_adam", "sSVN_adam"
is_stochastic: False

# seeds: [38,39,40,41,42] 

task: "mnist"

is_classification: True
task_dim: 10

lr: 1e-5
anneal: True

kernel_width: 1e-3 


data_location: "data/"
batch_size: 128

num_particles: 5
num_epochs: 5

model_selection_metric: 'NLL' # 'NLL' 'Cross Entropy'

likelihood_std: 1